### ISSUE TITLE
Python container

### ISSUE THREAD

**Issue by DannyDannyDanny** [DannyDannyDanny/burb#6]
To get started, I've written `server.py` to output three files:

```
# list dirs in current folder and write to file (files_in_here.txt)
...
# list dirs in parent folder and write to file (files_in_parent.txt)
...
# write absolute file path to file (absolute.txt)
...
```

After rebuilding, I run `docker ps` and see that the python container is not running (I guess that's because this script runs through once, dies and then the container ceases to exist. **Is that what happens?**

**Comment by ElDuderino420** [comment]
fixed scrub
